apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-workshop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:hashtagf/k8s-workshop.git
    targetRevision: main
    path: deployments
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
---

